<?xml version="1.0" encoding="UTF-8"?>

<service>
   <name>org.xito.testing</name>
   <display-name>Testing Service for JUnit</display-name>
   <desc></desc>
   <version>@project.version@</version>
   <service-cls></service-cls>
   <classpath>
      <lib path="xito-testing-@project.version@.jar"/>
      <lib path="junit.jar"/>
   </classpath>
</service>
