<?xml version="1.0" encoding="UTF-8"?>

<service>
   <name>org.xito.launcher</name>
   <display-name>Launcher Service</display-name>
   <desc>Service enables Java, JNLP, Applet, Web Browser, Execution</desc>
   <version>${project.version}</version>
   <service-cls>org.xito.launcher.LauncherService</service-cls>
   <classpath>
      <service-ref name="org.xito.xmldocs" href="../../../xmldocs/resources/xmldocs/xmldocs.srv"/>
      <service-ref name="org.xito.dazzle" href="../../../dazzle/resources/dazzle/dazzle.srv"/>
      <service-ref name="org.xito.prefs" href="../../../prefs/resources/prefs/prefs.srv"/>
      <lib path="../../build/libs/launcher.jar"/>
      <lib path="../../build/libs/jdom-1.1.jar"/>
      <lib path="../../build/libs/jtidy-r938.jar"/>
      <lib path="../../build/libs/jnlp.jar"/>
   </classpath>
</service>
