<?xml version="1.0" encoding="UTF-8"?>

<service>
   <name>test.app.MyApp</name>
   <display-name>Sample Application</display-name>
   <desc>This is a Sample Application</desc>
   <version>1.0.0</version>
   <service-cls>test.app.MyApp</service-cls>
   <append-to-classpath>true</append-to-classpath>
   <classpath>
      <lib path="sample.jar"/>
   </classpath>
</service>
