<?xml version="1.0" encoding="UTF-8"?>

<service>
   <name>org.jdesktop.jdic</name>
   <display-name>JDIC Service</display-name>
   <desc>Service wraps the Java Desktop Integration Components</desc>
   <version>${project.version}</version>
   <service-cls>org.xito.jdic.JDICService</service-cls>
   <classpath>
      <lib path="jdic.jar"/>
      <lib path="${project.build.finalName}.jar"/>
      <lib path="windows/jdic_stub_windows.jar" os="windows"/>
      <lib path="mac/jdic_stub_mac.jar" os="mac"/>      
   </classpath>
   <native-libs>
      <lib path="windows/jdic_windows.jar" os="windows"/>  
      <lib path="mac/jdic_mac.jar" os="mac"/>  
   </native-libs>
</service>
