<?xml version="1.0" encoding="UTF-8"?>

<service>
   <name>org.xito.about</name>
   <display-name>About Service</display-name>
   <desc>Service provides Application Environment Information</desc>
   <version>${project.version}</version>
   <service-cls>org.xito.about.AboutService</service-cls>
   <classpath>
      <lib path="${project.build.finalName}.jar"/>
   </classpath>
</service>
