<?xml version="1.0" encoding="UTF-8"?>

<service>
   <name>org.xito.prefs</name>
   <display-name>Preference Service</display-name>
   <desc>Preference Storage Service</desc>
   <version>${project.version}</version>
   <service-cls>org.xito.prefs.PrefManagerService</service-cls>
   <classpath>
      <lib path="${project.build.finalName}.jar"/>
   </classpath>
</service>
