<?xml version="1.0" encoding="UTF-8"?>

<service>
   <name>test.service7</name>
   <display-name>Service 7</display-name>
   <desc>This is a Test Service</desc>
   <version>1.0.0</version>
   <service-cls>test.Service7</service-cls>
   <classpath>
      <lib path="service7.jar"/>
   </classpath>
</service>
