<?xml version="1.0" encoding="UTF-8"?>

<service>
   <name>test.xito.dazzle_test</name>
   <display-name>Dazzle Test</display-name>
   <version>1.0.0</version>
   <service-cls>test.xito.dazzle.TestStackPanel</service-cls>
   <classpath>
      <service-ref name="org.xito.dazzle"/>
      <lib path="xito-dazzle-test.jar"/>
   </classpath>
</service>
