<?xml version="1.0" encoding="UTF-8"?>

<service>
   <name>org.xito.blxtesting</name>
   <display-name>Testing Service for BLX</display-name>
   <desc></desc>
   <version></version>
   <service-cls>test.testcases.BLXTestingService</service-cls>
   <classpath>
      <service-ref name="test.srvext.testextsrv" href="testextsrv.srv"/>
      <service-ref name="org.xito.testing" href="../xito-testing/xito-testing.srv"/>
      <lib path="xito-blx-test.jar"/>
   </classpath>
</service>
